### PR TITLE
Include `libsgsl-dev` package to run Peter's cloud masking algorithm

### PR DESCRIPTION
**Pull request by harshurampur**
A requirement package written in C++ and requires the library to run Peter's time-series cloud masking algorithm on Sentinel 2 data

### CODE REVIEW

**Comment by Kirill888** [comment]
should this also include python package?

**Comment by harshurampur** [comment]
No, does not have any dependencies on other packages.

**Comment by Kirill888** [comment]
what I meant to say is: should this PR also include installation of the python package that uses the c library being installed?

**Comment by harshurampur** [comment]
I don't know, looking at it https://www.gnu.org/software/gsl/ it might not .. I can check with Peter

**Comment by harshurampur** [comment]
I checked with Peter he just needs this library, thats it.

**Review by Kirill888 — APPROVED** [review]

**Pull request merged**
